kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: dotnetconf
spec:
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnetconf
    spec:
      restartPolicy: Always
      containers:
        - name: dotnetconf
          image: selcukusta/dotnetconf:1.0.0
          imagePullPolicy: Always
          env:
            - name: FROM_ENV
              value: "It's from environment!"
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: secrets
              mountPath: /from-secret
              readOnly: true
          resources:
            limits:
              memory: "400Mi"
      volumes:
        - name: secrets
          secret:
            secretName: app-secret
---
kind: Service
apiVersion: v1
metadata:
  name: dotnetconf
  labels:
    name: dotnetconf
spec:
  type: ClusterIP
  selector:
    app: dotnetconf
  ports:
    - port: 80
      name: http
      targetPort: 80
